#!/bin/bash

# Template the php-fpm.conf file with the environment variables
sed -ie "s|^pm\.max_children =.*$|pm\.max_children = ${PM_MAX_CHILDREN}|g" /usr/local/etc/php-fpm.d/zz-php.conf
sed -ie "s|^pm\.start_servers =.*$|pm\.start_servers = ${PM_START_SERVERS}|g" /usr/local/etc/php-fpm.d/zz-php.conf
sed -ie "s|^pm\.min_spare_servers =.*$|pm\.min_spare_servers = ${PM_MIN_SPARE_SERVERS}|g" /usr/local/etc/php-fpm.d/zz-php.conf
sed -ie "s|^pm\.max_spare_servers =.*$|pm\.max_spare_servers = ${PM_MAX_SPARE_SERVERS}|g" /usr/local/etc/php-fpm.d/zz-php.conf
sed -ie "s|^pm\.max_requests =.*$|pm\.max_requests = ${PM_MAX_REQUESTS}|g" /usr/local/etc/php-fpm.d/zz-php.conf

exec /usr/local/sbin/php-fpm